name: Validate Step 19

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - src/typescript/src/config.service.ts
      - .tutorial/state.env
      - .tutorial-started

jobs:
  validate:
    permissions:
      contents: write
    uses: ./.github/workflows/reusable-step.yml
    with:
      step_number: '19'